### ISSUE TITLE
【3.10】打卡

### ISSUE THREAD

**Issue by simpleboy918** [labuladong/challenge#85]
https://leetcode-cn.com/problems/merge-two-sorted-lists/solution/310-he-bing-liang-ge-you-xu-lian-biao-by-do12/

**Comment by yellow0816** [comment]
https://leetcode-cn.com/problems/merge-two-sorted-lists/solution/day1-310-by-hai-di-yue-shi-tian-shang-yu-xmgk/

**Comment by wanggithub2020** [comment]
https://leetcode-cn.com/problems/merge-two-sorted-lists/solution/nei-cun-xiao-hao-you-dian-da-de-jie-fa-b-iep3/

**Comment by tangpingba** [comment]
打错地方了，去这里跟帖😂 https://github.com/labuladong/challenge/issues/81

**Comment by QuannengLiu** [comment]
https://leetcode-cn.com/problems/merge-two-sorted-lists/solution/he-bing-liang-ge-you-xu-lian-biao-by-lan-6wou/
